spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: yali
    url: jdbc:mysql://localhost:3306/myshop?characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&useSSL=true&zeroDateTimeBehavior=convertToNull&autoReconnect = true
    hikari:
      maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    com.wzh: debug
mybatis:
  mapper-locations: classpath:mappers/**/*.xml

